name: Bug report
description: Report a defect in scripts, bot behavior, or automation.
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: area
    attributes:
      label: Area
      description: Where is the issue?
      placeholder: "mail-pipeline / telegram-dashboard / finance / scheduler"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual result
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/trace
      description: Paste short relevant lines only (no secrets).
      placeholder: "00_INBOX/_ROUTER_LOGS/... lines"

  - type: checkboxes
    id: checklist
    attributes:
      label: Safety checks
      options:
        - label: I removed secrets/tokens from the report
          required: true
