$here=$PSScriptRoot
$addType=Join-Path $here "add_type.ps1"
$addRule=Join-Path $here "add_rule.ps1"

$rules=@("ZBIERZ_DANE_MIN","ODPOWIEDZ_PISEMNA_TYLKO","ZALACZNIKI_I_DOWODY","TERMINY_I_DEADLINES","NIE_UZNAWAC_DLUGU","STATUS_SWITCH")
$types=@("UMOWA_ROZWIAZANIE_ZMIANA_ADRESU","UMOWA_KARA_UMOWNA","OPERATOR_ODMOWA_UZNANIA_DOKUMENTU","WEZWANIE_DO_ZAPLATY","ZUS_SKLADKI_TERMIN","ZUS_ZALEGLOSC","AUTO_OC_ODMOWA","AUTO_KREDYT_RATA_SPOR","KLIENT_REKLAMACJA","KLIENT_ZMIANA_ZAKRESU","KLIENT_WYCENA_ZAPYTANIE")

foreach($r in $rules){ & $addRule -RULE_ID $r }
foreach($t in $types){ & $addType -TYPE_ID $t }
